feat: filemanager sea-orm entities
umccr/orcabus pull request #357
Opened 2024-06-17 23:45 UTC by mmalenic

Closes #314

### Changes
* Setups up sea-orm entity generation in a build.rs script, and includes the generated code as part of the file manager.
    * A new `filemanager-build` crate is used for better code organisation.

Leaving this as a draft for now until the phase 1 deployment is complete.

2024-06-17 23:49 UTC, mmalenic commented on lib/workload/stateless/stacks/filemanager/filemanager-build/src/entities.rs
> +    );
This is required to be able to include the module in the `filemanager` crate using `include!(concat!(env!("OUT_DIR"), "/entities.rs"))`. My IDE is able to pick up these modules okay, AFAIK vscode should work too.

2024-06-17 23:49 UTC, mmalenic commented on lib/workload/stateless/stacks/filemanager/filemanager-build/src/error.rs
> +    }
Using miette for nicer compile/build error printing. `#[track_caller]` is useful to print line information about where an error occurred, similar to the Rust compiler.

2024-06-25 05:41 UTC, brainstorm requested changes
If I understand the code correctly, `filemanager-build/src/entities.rs` generates ... `entities.rs` that will be `include!`-d on `mod.rs`... for easier source code navigation I would prefix with `gen_` or similar (i.e `gen_entities.rs`), otherwise it gets confusing what codegens what (`entities.rs` codegenerating another `entities.rs` somewhere else?) :-S

If filemanager-build/src/entities.rs is the generated file, I'd put a header that states that: `Autogenerated file, see the other file gen_entities.rs for its source/generation`.

2024-06-25 05:53 UTC, mmalenic commented
That's a good call, `filemanager-build/src/entities.rs` is not a generated file, it does the generation step. So I think for clarity, I'll rename that to `gen_entities.rs`. This creates a file called `${OUT_DIR}/entities.rs` :see_no_evil: ... That file should have a comment in it, and could be called `entities.rs`. Or maybe `gen.rs` so that it's clear where it's included that it represents generated code?

2024-06-25 05:55 UTC, brainstorm commented
> That file should have a comment in it, and could be called `entities.rs`. Or maybe `gen.rs` so that it's clear where it's included that it represents generated code?

Either way works, just make it clear **which generates and which is generated** ;)

2024-06-25 23:05 UTC, brainstorm approved these changes

2024-06-26 00:20 UTC, victorskl approved these changes
LGTM!

2024-06-26 07:10 UTC, merged